using Content.Shared._VXS14.Mortar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._VXS14.Mortar;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class BallisticCalculatorWindow : DefaultWindow
{
    private BallisticCalculatorEui? _eui;

    public BallisticCalculatorWindow()
    {
        RobustXamlLoader.Load(this);

        Title = "Mortar Ballistic Calculator";

        MortarX.IsValid = value => value >= -10000f && value <= 10000f;
        MortarY.IsValid = value => value >= -10000f && value <= 10000f;
        DeviationX.IsValid = value => value >= -10000f && value <= 10000f;
        DeviationY.IsValid = value => value >= -10000f && value <= 10000f;

        CalculateButton.OnPressed += OnCalculatePressed;
    }

    public void SetEui(BallisticCalculatorEui eui)
    {
        _eui = eui;
    }

    public void UpdateSnapshot(MortarBallisticCalculatorEuiMsg.Snapshot snapshot)
    {
        ObserverLabel.Text = $"Observer: X={snapshot.ObserverX:0.0}, Y={snapshot.ObserverY:0.0}";
        TargetLabel.Text = "Target: enter dX/dY and press Calculate";

        if (string.IsNullOrEmpty(ErrorLabel.Text))
            return;

        ErrorLabel.Text = string.Empty;
    }

    public void UpdateResult(MortarBallisticCalculatorEuiMsg.Result result)
    {
        TargetLabel.Text = $"Target: X={result.TargetX:0.0}, Y={result.TargetY:0.0}";
        DistanceLabel.Text = $"Distance: {result.MortarToTargetDistance:0.0} tiles";
        FlightTimeLabel.Text = $"Flight time: {result.FlightTimeSeconds:0.00} s";
        DeviationLabel.Text = $"Expected deviation: {result.ExpectedDeviation:0.00} tiles";
        ErrorLabel.Text = string.Empty;
    }

    public void ShowError(string message)
    {
        ErrorLabel.Text = message;
    }

    private void OnCalculatePressed(ButtonEventArgs args)
    {
        _eui?.SendCalculate(MortarX.Value, MortarY.Value, DeviationX.Value, DeviationY.Value);
    }
}
