using System.Globalization;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._VXS14.Mortar;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class BasicCalculatorWindow : DefaultWindow
{
    private double? _accumulator;
    private char? _pendingOp;
    private bool _replaceDisplay = true;

    public BasicCalculatorWindow()
    {
        RobustXamlLoader.Load(this);
        Title = "Calculator";

        WireDigit(Btn0, "0");
        WireDigit(Btn1, "1");
        WireDigit(Btn2, "2");
        WireDigit(Btn3, "3");
        WireDigit(Btn4, "4");
        WireDigit(Btn5, "5");
        WireDigit(Btn6, "6");
        WireDigit(Btn7, "7");
        WireDigit(Btn8, "8");
        WireDigit(Btn9, "9");

        BtnDot.OnPressed += _ => AddDot();
        BtnBack.OnPressed += _ => Backspace();
        BtnCe.OnPressed += _ => ClearEntry();
        BtnC.OnPressed += _ => ClearAll();
        BtnSign.OnPressed += _ => ToggleSign();

        BtnAdd.OnPressed += _ => SetOperation('+');
        BtnSub.OnPressed += _ => SetOperation('-');
        BtnMul.OnPressed += _ => SetOperation('*');
        BtnDiv.OnPressed += _ => SetOperation('/');
        BtnEq.OnPressed += _ => EvaluatePending();

        UpdateDisplay("0");
    }

    private void WireDigit(Button button, string value)
    {
        button.OnPressed += _ => AppendDigit(value);
    }

    private void AppendDigit(string digit)
    {
        string text = _replaceDisplay ? string.Empty : DisplayLabel?.Text ?? string.Empty;

        if (text == "0")
            text = string.Empty;

        text += digit;
        UpdateDisplay(text.Length == 0 ? "0" : text);
        _replaceDisplay = false;
    }

    private void AddDot()
    {
        string text = _replaceDisplay ? "0" : DisplayLabel?.Text ?? "0";

        if (!text.Contains('.'))
            text += ".";

        UpdateDisplay(text);
        _replaceDisplay = false;
    }

    private void Backspace()
    {
        if (_replaceDisplay)
            return;

        string text = DisplayLabel?.Text ?? string.Empty;
        if (text.Length <= 1 || (text.Length == 2 && text.StartsWith('-')))
        {
            UpdateDisplay("0");
            _replaceDisplay = true;
            return;
        }

        UpdateDisplay(text[..^1]);
    }

    private void ClearEntry()
    {
        UpdateDisplay("0");
        _replaceDisplay = true;
    }

    private void ClearAll()
    {
        _accumulator = null;
        _pendingOp = null;
        if (ExpressionLabel != null)
            ExpressionLabel.Text = string.Empty;
        UpdateDisplay("0");
        _replaceDisplay = true;
    }

    private void ToggleSign()
    {
        string display = DisplayLabel?.Text ?? "0";

        if (display == "0")
            return;

        if (display.StartsWith('-'))
            UpdateDisplay(display[1..]);
        else
            UpdateDisplay($"-{display}");
    }

    private void SetOperation(char operation)
    {
        if (!_replaceDisplay)
            CommitDisplay();

        _pendingOp = operation;
        if (ExpressionLabel != null)
        {
            ExpressionLabel.Text = _accumulator.HasValue
                ? $"{FormatNumber(_accumulator.Value)} {operation}"
                : string.Empty;
        }
        _replaceDisplay = true;
    }

    private void EvaluatePending()
    {
        if (!_pendingOp.HasValue)
            return;

        if (!_replaceDisplay)
            CommitDisplay();

        _pendingOp = null;
        if (ExpressionLabel != null)
            ExpressionLabel.Text = string.Empty;
        _replaceDisplay = true;
    }

    private void CommitDisplay()
    {
        string display = DisplayLabel?.Text ?? "0";
        if (!double.TryParse(display, NumberStyles.Float, CultureInfo.InvariantCulture, out var current))
            return;

        if (!_accumulator.HasValue)
        {
            _accumulator = current;
            UpdateDisplay(FormatNumber(_accumulator.Value));
            return;
        }

        _accumulator = _pendingOp switch
        {
            '+' => _accumulator.Value + current,
            '-' => _accumulator.Value - current,
            '*' => _accumulator.Value * current,
            '/' => Math.Abs(current) < 0.0000001 ? double.NaN : _accumulator.Value / current,
            _ => current,
        };

        UpdateDisplay(double.IsNaN(_accumulator.Value) ? "Error" : FormatNumber(_accumulator.Value));

        if (double.IsNaN(_accumulator.Value))
        {
            _accumulator = null;
            _pendingOp = null;
            if (ExpressionLabel != null)
                ExpressionLabel.Text = string.Empty;
            _replaceDisplay = true;
        }
    }

    private static string FormatNumber(double value)
    {
        return value.ToString("0.########", CultureInfo.InvariantCulture);
    }

    private void UpdateDisplay(string text)
    {
        if (DisplayLabel != null)
            DisplayLabel.Text = text;
    }
}
