using System.Numerics;
using Content.Shared.Explosion;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.OptionButton;
using Content.Shared._VXS14.Mortar;
using Content.Client.Eui;

namespace Content.Client._VXS14.Mortar;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class MortarWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _conHost = default!;
    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly SharedTransformSystem _transform = default!;

    private MortarEui? _eui;
    private MapId _mapData = new();
    /// <summary>
    ///     Used to prevent unnecessary preview updates when setting fields (e.g., updating position)..
    /// </summary>
    private bool _pausePreview;

    // Default ranges in case configuration isn't received
    private float _minOffsetX = -50f;
    private float _maxOffsetX = 50f;
    private float _minOffsetY = -50f;
    private float _maxOffsetY = 50f;

    public MortarWindow()
    {
        Logger.InfoS("mortar-window", "Attempting to load XAML for MortarWindow");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _transform = _entMan.System<TransformSystem>();
    }

    public void SetEui(MortarEui eui)
    {
        _eui = eui;

        Recentre.OnPressed += (_) => ResetOffsets();
        Spawn.OnPressed += SubmitButtonOnOnPressed;

        // Initialize default buttons for easy value adjustment
        OffsetX.InitDefaultButtons();
        OffsetY.InitDefaultButtons();

        OffsetX.ValueChanged += (args) => ValidateAndPreview();
        OffsetY.ValueChanged += (args) => ValidateAndPreview();
    }

    public void SetMortarConfig(float minOffsetX, float maxOffsetX, float minOffsetY, float maxOffsetY)
    {
        _minOffsetX = minOffsetX;
        _maxOffsetX = maxOffsetX;
        _minOffsetY = minOffsetY;
        _maxOffsetY = maxOffsetY;

        // Apply the ranges to the SpinBox controls
        OffsetX.IsValid = (value) => value >= _minOffsetX && value <= _maxOffsetX;
        OffsetY.IsValid = (value) => value >= _minOffsetY && value <= _maxOffsetY;
    }

    protected override void EnteredTree()
    {
        ResetOffsets();
    }

    /// <summary>
    ///     Reset the offset values to a safe default.
    /// </summary>
    private void ResetOffsets()
    {
        _pausePreview = true;
        OffsetX.Value = 5; // Safe default offset
        OffsetY.Value = 0;
        _pausePreview = false;
        UpdatePreview();
    }

    private void UpdatePreview()
    {
        if (_pausePreview)
            return;
    }

    private void ValidateAndPreview()
    {
        // Let the server handle all validation - just update the preview
        UpdatePreview();
    }

     private void SubmitButtonOnOnPressed(ButtonEventArgs args)
     {
        // Send the offset values to the server
        _eui?.SendCords(new Vector2(OffsetX.Value, OffsetY.Value));
     }
}
