- type: department
  id: USMC
  name: department-USMC-name
  description: department-USMC-description
  color: "#203564"
  weight: 85
  roles:
  - USMCSquadLeader
  - USMCRifleman
  - USMCAutomaticRifleman
  - USMCMedic
  - USMCRecon

- type: department
  id: USSF
  name: department-USSF-name
  description: department-USSF-description
  color: "#203564"
  weight: 84
  roles:
  - USSFCaptain
  - USSFCrewman
  - USSFFighterPilot

- type: department
  id: ARNG
  name: department-NG-name
  description: department-NG-description
  color: "#203564"
  weight: 83
  roles:
#  - NGLieutenant
  - NGSquadLeader
  - NGRifleman
  - NGAutomaticRifleman
  - NGMedic
  - NGRecon
  editorHidden: true

- type: department
  id: VDV
  name: department-VDV-name
  description: department-VDV-description
  color: "#a02829"
  weight: 75
  roles:
  - VDVSquadLeader
  - VDVRifleman
  - VDVAutomaticRifleman
  - VDVMedic
  - VDVRecon

- type: department
  id: VKS
  name: department-VKS-name
  description: department-VKS-description
  color: "#203564"
  weight: 74
  roles:
  - VKSCaptain
  - VKSCrewman
  - VKSFighterPilot

- type: department
  id: WPS
  name: department-WPS-name
  description: department-WPS-description
  color: "#203564"
  weight: 60
  roles:
  - WPSSecurityOfficer
  - WPSWarden
  - WPSMarshal
