## NATO
# US

- type: department
  id: USMC
  name: department-USMC-name
  description: department-USMC-description
  color: "#203564"
  weight: 85
  roles:
  - USMCSquadLeader
  - USMCRifleman
  - USMCAutomaticRifleman
  - USMCMedic
  - USMCRecon

- type: department
  id: USSF
  name: department-USSF-name
  description: department-USSF-description
  color: "#203564"
  weight: 84
  roles:
  - USSFCaptain
  - USSFCrewman
  - USSFFighterPilot

- type: department
  id: ARNG
  name: department-NG-name
  description: department-NG-description
  color: "#203564"
  weight: 83
  roles:
  - NGLieutenant
  - NGSquadLeader
  - NGRifleman
  - NGAutomaticRifleman
  - NGMedic
  - NGRecon

- type: department
  id: USPD
  name: department-USPD-name
  description: department-USPD-description
  color: "#203564"
  weight: 45
  roles:
  - USPDChief
  - USPDWarden
  - USPDOfficer

## PACT
# RU

- type: department
  id: VDV
  name: department-VDV-name
  description: department-VDV-description
  color: "#a02829"
  weight: 65
  roles:
  - VDVSquadLeader
  - VDVRifleman
  - VDVAutomaticRifleman
  - VDVMedic
  - VDVRecon

- type: department
  id: VKS
  name: department-VKS-name
  description: department-VKS-description
  color: "#203564"
  weight: 64
  roles:
  - VKSCaptain
  - VKSCrewman
  - VKSFighterPilot

- type: department
  id: OMON
  name: department-OMON-name
  description: department-OMON-description
  color: "#203564"
  weight: 62
  roles:
  - OMONLieutenant # Unit Commander
  - OMONSquadLeader # Sergeant
  - OMONRifleman # Riot Officer
  editorHidden: true

## IND

- type: department
  id: WPS
  name: department-WPS-name
  description: department-WPS-description
  color: "#203564"
  weight: 50
  roles:
  - WPSSecurityOfficer
  - WPSWarden
  - WPSMarshal

- type: department
  id: BF14Civilian
  name: department-Civilian
  description: department-NFCivilian-description # Frontier
  color: "#9FED58"
  weight: 1
  roles:
  - CivilianUS
  - RUScav
  - RUScavGuard
  - RUScavBoss