- type: startingGear
  id: BF14DeathmatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorWebVestSecEmpty
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackRucksackBlack
    neck: FlashlightMilitaryUS
    suitstorage: WeaponRifleUSM4
    pocket1: WeaponPistolBEFiveSeven
    pocket2: PouchFirstAidFilled
