- type: startingGear
  id: BF14DeathmatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryColorWhiteTDM
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatHelmetUSFAST
    outerClothing: ClothingOuterArmorKevlarVest
    shoes: ClothingShoesBootsJackFilled
    neck: FlashlightMilitaryUS
    suitstorage: WeaponRifleUSM16A2
    pocket1: PouchMagsLargeFilledSTANAG
    pocket2: PouchFirstAidFilled

- type: startingGear
  id: BF14GoonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCombatSuitDigitalBlack
    ears: ClothingHeadsetGrey
    balaclava: ClothingBalaclavaSkiMaskMouthBlack
    outerClothing: ClothingOuterArmorWebVestSec
    belt: ClothingBeltStationSecurityFilledFBI
    shoes: ClothingShoesBootsJackFilled
    pocket2: PouchFirstAidFilled

- type: startingGear
  id: BF14FBIGoonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPlain
    ears: ClothingHeadsetAltUS
    balaclava: ClothingBalaclavaClassicMouthRangerGreen
    outerClothing: ClothingOuterArmorPlateCarrierTan
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltStationSecurityFilledFBI
    shoes: ClothingShoesBootsJackFilled
    pocket2: PouchFirstAidFilled

- type: startingGear
  id: BF14FBISMGGoonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPlain
    ears: ClothingHeadsetAltUS
    balaclava: ClothingBalaclavaClassicMouthRangerGreen
    outerClothing: ClothingOuterArmorPlateCarrierTan
    suitstorage: WeaponSubmachinegunDEMP510
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltStationSecurityFilledFBISMG
    shoes: ClothingShoesBootsJackFilled
    pocket2: PouchFirstAidFilled

#region TDM

- type: startingGear
  id: BF14TDMGearBlue
  equipment:
    id: USMCRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorBlueTDM
    head: ClothingHeadHatHelmetUSFAST
    balaclava: ClothingBalaclavaMilitary
    ears: ClothingHeadsetAltUS
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFBlue
    leftarmband: FlashlightMilitaryUS
    suitstorage: WeaponRifleDEG36K
    pocket1: WeaponPistolATGlock20
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanister
    - CrowbarRed
    - DefensiveGrenadeUSM67
    - Tourniquet
    - BF14PinpointerBlueIntel
    belt:
    - MagazinePistolGlock20
    - MagazinePistolGlock20
    - MagazineRifleG36
    - MagazineRifleG36
    - MagazineRifleG36
    - MagazineRifleG36
    - MagazineRifleG36

- type: startingGear
  id: BF14TDMGearBluePointman
  equipment:
    id: USMCRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorBlueTDM
    head: ClothingHeadHatHelmetUSFASTMandible
    balaclava: ClothingBalaclavaMilitary
    ears: ClothingHeadsetAltUS
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVExtendedRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFBlue
    leftarmband: FlashlightMilitaryUS
    suitstorage: WeaponSubmachinegunDEMP5A4
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanister
    - CrowbarRed
    - FlashbangGrenadeUSM84
    - FlashbangGrenadeUSM84
    - Tourniquet
    - BF14PinpointerBlueIntel
    belt:
    - MagazineSubmachinegunMP5
    - MagazineSubmachinegunMP5
    - MagazineSubmachinegunMP5
    - MagazineSubmachinegunMP5
    - MagazineSubmachinegunMP5
    - MagazineSubmachinegunMP5

- type: startingGear
  id: BF14TDMGearBlueMarksman
  equipment:
    id: USMCRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorBlueReconTDM
    mask: ClothingMaskNeckGaiter
    head: ClothingHeadHatBoonie
    ears: ClothingHeadsetAltUS
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFBlue
    leftarmband: FlashlightMilitaryUS
    suitstorage: WeaponSniperUSM14EBR
    pocket1: WeaponPistolATGlock20
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanister
    - CrowbarRed
    - SmokeGrenadeUSM18
    - Tourniquet
    - BF14PinpointerBlueIntel
    belt:
    - MagazinePistolGlock20
    - MagazinePistolGlock20
    - MagazineRifleM14
    - MagazineRifleM14
    - MagazineRifleM14
    - MagazineRifleM14
    - MagazineRifleM14

- type: startingGear
  id: BF14TDMGearRed
  equipment:
    id: VDVRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorRedTDM
    head: ClothingHeadHatHelmetUSFAST
    balaclava: ClothingBalaclavaMilitary
    ears: ClothingHeadsetAltRU
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFRed
    leftarmband: FlashlightMilitaryAlt
    suitstorage: WeaponRifleRUAK74M
    pocket1: WeaponPistolATGlock20
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanisterRed
    - CrowbarRed
    - DefensiveGrenadeUSM67
    - Tourniquet
    - BF14PinpointerRedIntel
    belt:
    - MagazinePistolGlock20
    - MagazinePistolGlock20
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black

- type: startingGear
  id: BF14TDMGearRedPointman
  equipment:
    id: VDVRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorRedTDM
    head: ClothingHeadHatHelmetUSFASTMandible
    balaclava: ClothingBalaclavaMilitary
    ears: ClothingHeadsetAltUS
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVExtendedRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFRed
    leftarmband: FlashlightMilitaryUS
    suitstorage: WeaponSubmachinegunRUVityaz
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanisterRed
    - CrowbarRed
    - FlashbangGrenadeRUZarya
    - FlashbangGrenadeRUZarya
    - Tourniquet
    - BF14PinpointerRedIntel
    belt:
    - MagazineSubmachinegunVityaz
    - MagazineSubmachinegunVityaz
    - MagazineSubmachinegunVityaz
    - MagazineSubmachinegunVityaz
    - MagazineSubmachinegunVityaz
    - MagazineSubmachinegunVityaz

- type: startingGear
  id: BF14TDMGearRedMarksman
  equipment:
    id: VDVRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorRedReconTDM
    mask: ClothingMaskNeckGaiter
    head: ClothingHeadHatBoonie
    ears: ClothingHeadsetAltUS
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFRed
    leftarmband: FlashlightMilitaryUS
    suitstorage: WeaponSniperRUSVDS
    pocket1: WeaponPistolATGlock20
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanisterRed
    - CrowbarRed
    - BoxGrenadesRDG2
    - Tourniquet
    - BF14PinpointerRedIntel
    belt:
    - MagazinePistolGlock20
    - MagazinePistolGlock20
    - MagazineSniperSVD
    - MagazineSniperSVD
    - MagazineSniperSVD
    - MagazineSniperSVD
    - MagazineSniperSVD
