- type: job
  id: OMONSquadLeader
  name: job-name-omon-squadleader
  description: job-description-omon-squadleader
  playTimeTracker: JobOMONSquadLeader
  weight: 72
  startingGear: OMONSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconPACTAllySquadleader"
  requireAdminNotify: true
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    - Esperanto
    languagesUnderstood:
    - Russian
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  # - !type:AddComponentSpecial
  #   components:
  #     # COMMENTED OUT: ChatRank and HullrotFaction not supported
  #     # - type: ChatRank
  #     #   rank: BF-rank-private
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: OMONSquadLeaderGear
  equipment:
    id: VDVSquadLeaderPDA # TODO
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRU
    jumpsuit: ClothingUniformJumpsuitRUOMON
    outerClothing: ClothingOuterArmorWebVestSec
    shoes: ClothingShoesBootsJackFilled
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledVDVScout
    rightarmband: ClothingArmbandThighHolsterFilledRU
  storage:
    back:
    - ArmorPlateLight
    - BoxPinpointerUniversalPACT
    - MagazinePistolMP443
    - MagazinePistolMP443
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - SyndicateWhistle
    - Tourniquet
    - Zipties
