- type: job
  id: FSBSquadLeader
  name: job-name-fsb-squadleader
  description: job-description-fsb-squadleader
  playTimeTracker: JobFSBSquadLeader
  weight: 78
  startingGear: FSBSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconPACTSquadleader"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    - English
    - Esperanto
    languagesUnderstood:
    - Russian
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - FSB
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTMedical
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: FSBSquadLeaderGear
  equipment:
    id: FSBSquadLeaderPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK74
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR # Gorka
    head: ClothingHeadHatHelmetRUEMR # blank
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    outerClothing: ClothingOuterArmorPlateCarrierBlack
    shoes: ClothingShoesBootsJackFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeFSB
    suitstorage: WeaponRifleRUAK74FSB
    pocket1: PouchMedkitFilledMarsoc
    pocket2: PouchGrenadesFilledVDVRifleman
    leftarmband: ClothingArmbandDumpPouchBlack
    rightarmband: ClothingArmbandThighHolsterFilledRUSR1MP
    wallet: ClothingWalletLeatherBlack
  storage:
    back:
    - ArmorPlateMedium
    - HandheldStationMapUnpowered
    - MagazinePistolSR1MP
    - MagazinePistolSR1MP
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - CrowbarRed
    - DoubleEmergencyOxygenTankFilled
    - SyndicateWhistle
    - Tourniquet
    - Zipties

- type: startingGear
  id: FSBSquadLeaderGearEVA
  equipment:
    id: FSBSquadLeaderPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK74
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR # Gorka
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    outerClothing: ClothingOuterVoidsuitRussianCombat
    shoes: ClothingShoesBootsMagAshenFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeFSB
    suitstorage: WeaponRifleRUAK74FSB
    pocket1: PouchMedkitFilledMarsoc
    pocket2: PouchGrenadesFilledVDVRifleman
    leftarmband: ClothingArmbandDumpPouchBlack
    rightarmband: ClothingArmbandThighHolsterFilledRUSR1MP
    wallet: ClothingWalletLeatherBlack
  storage:
    back:
    - ArmorPlateMedium
    - HandheldStationMapUnpowered
    - MagazinePistolSR1MP
    - MagazinePistolSR1MP
    - CrowbarRed
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - DoubleEmergencyOxygenTankFilled
    - SyndicateWhistle
    - Tourniquet
    - Zipties
