## NATO
# US
- type: entity
  id: CrateSecgearNATOFilledM249Para
  suffix: Filled, M249 Para
  parent: CrateSecgear
  name: M249 Para crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponMachineGunUSM249Para
          amount: 2
        - id: MagazineBeltBoxM249
          amount: 4
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledSMAW
  suffix: Filled, SMAW
  parent: CrateSecgear
  name: SMAW crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSSMAW
          amount: 2
        - id: CartridgeSMAWHEAA
          amount: 4
        - id: CartridgeSMAWNE
          amount: 4
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledAT4
  suffix: Filled, AT4
  parent: CrateSecgear
  name: AT4 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSAT4
          amount: 5
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM27IAR
  suffix: Filled, M27IAR
  parent: CrateSecgear
  name: M27-IAR crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM27IAR
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM16A4
  suffix: Filled, M16A4
  parent: CrateSecgear
  name: M16A4 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM16A4
          amount: 10
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM4A1
  suffix: Filled, M4A1
  parent: CrateSecgear
  name: M16A4 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM4A1
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM870
  suffix: Filled, M870
  parent: CrateSecgear
  name: M870 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunUSM870
          amount: 5
        - id: ShellBoxBF12GaugeBuckshot
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM590
  suffix: Filled, M590
  parent: CrateSecgear
  name: M590 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunUSM590
          amount: 5
        - id: ShellBoxBF12GaugeBreaching
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

## PACT
# RU

- type: entity
  id: CrateSecgearPACTFilledAK12
  suffix: Filled, AK-12
  parent: CrateSecgear
  name: AK-12 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK12
          amount: 10
        - id: BoxMagazineAK12
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledAK74
  suffix: Filled, AK-74
  parent: CrateSecgear
  name: AK-74 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK74
          amount: 10
        - id: BoxMagazineAK74
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledAK203
  suffix: Filled, AK-203
  parent: CrateSecgear
  name: AK-203 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK203
          amount: 5
        - id: BoxMagazineAK203
          amount: 2
        - id: ClothingUniformJumpsuitCombatSuitDigitalRed
          amount: 5
        - id: ClothingHelmetCoverRedDigital
          amount: 5
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledSV98
  suffix: Filled, SV-98
  parent: CrateSecgear
  name: SV-98 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperRUSV98
          amount: 2
        - id: BoxMagazineSV98AP
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledKSK
  suffix: Filled, KSK
  parent: CrateSecgear
  name: KSK crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunRUKSK
          amount: 2
        - id: BoxMagazineKSKBuckshot
          amount: 2
        - id: BoxMagazineKSKSlug
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledPKM
  suffix: Filled, PKM
  parent: CrateSecgear
  name: PKM crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponMachineGunRUPKM
          amount: 2
        - id: MagazineBeltBoxPKM
          amount: 4
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPG7
  suffix: Filled, RPG-7
  parent: CrateSecgear
  name: RPG-7 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherRURPG7
          amount: 2
        - id: CartridgeRPG7HEAT
          amount: 4
        - id: CartridgeRPG7Frag
          amount: 4
  - type: AccessReader
    access: [["PACTSoldier"]]
