- type: job
  id: RUScavBoss
  name: Scavenger leader
  description: A local scavenger gang leader. you rule these lands, your say is final.
  playTimeTracker: JobRUScavBoss
  weight: 20
  startingGear: RUScavBossGear
  alwaysUseSpawner: true
  icon: "JobIconINDCaptain"
  requireAdminNotify: false
  supervisors: Nobody, youre the king of the world baby!
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  access:
  - Maintenance

- type: startingGear
  id: RUScavBossGear # other gear is in the stronghold armory
  equipment:
    ears: ClothingHeadsetAltScav
    jumpsuit: ClothingUniformJumpsuitCombatScavBoss
    head: ClothingHeadHatHelmetRUAltyn
    outerClothing: ClothingOuterArmorPlateCarrierHeavy
    shoes: ClothingShoesBootsJackFilled
    pocket1: PouchFirstAidFilled
    rightarmband: ClothingArmbandGraeves
    leftarmband: ClothingArmbandVambrace