## US

# USMC
- type: playTimeTracker
  id: JobUSMCSquadLeader

- type: playTimeTracker
  id: JobUSMCRifleman

- type: playTimeTracker
  id: JobUSMCAutomaticRifleman

- type: playTimeTracker
  id: JobUSMCMedic

- type: playTimeTracker
  id: JobUSMCRecon

# USMC - MARSOC

- type: playTimeTracker
  id: JobMARSOCSquadLeader

- type: playTimeTracker
  id: JobMARSOCRifleman

- type: playTimeTracker
  id: JobMARSOCAutomaticRifleman

- type: playTimeTracker
  id: JobMARSOCMedic

# USMC - HECU

- type: playTimeTracker
  id: JobHECUSquadLeader

- type: playTimeTracker
  id: JobHECURifleman

- type: playTimeTracker
  id: JobHECUSupport

- type: playTimeTracker
  id: JobHECUMedic

# USSF

- type: playTimeTracker
  id: JobUSSFCaptain

- type: playTimeTracker
  id: JobUSSFCrewman

- type: playTimeTracker
  id: JobUSSFFighterPilot

# National Guard

- type: playTimeTracker
  id: JobNGLieutenant

- type: playTimeTracker
  id: JobNGSquadLeader

- type: playTimeTracker
  id: JobNGRifleman

- type: playTimeTracker
  id: JobNGAutomaticRifleman

- type: playTimeTracker
  id: JobNGMedic

- type: playTimeTracker
  id: JobNGRecon

# US Police

- type: playTimeTracker
  id: JobUSPDChief

- type: playTimeTracker
  id: JobUSPDWarden

- type: playTimeTracker
  id: JobUSPDOfficer

## RU

# VDV

- type: playTimeTracker
  id: JobVDVSquadLeader

- type: playTimeTracker
  id: JobVDVRifleman

- type: playTimeTracker
  id: JobVDVAutomaticRifleman

- type: playTimeTracker
  id: JobVDVMedic

- type: playTimeTracker
  id: JobVDVRecon

# FSB

- type: playTimeTracker
  id: JobFSBSquadLeader

- type: playTimeTracker
  id: JobFSBRifleman

- type: playTimeTracker
  id: JobFSBSupport

- type: playTimeTracker
  id: JobFSBMedic

- type: playTimeTracker
  id: JobFSBRecon

# VKS

- type: playTimeTracker
  id: JobVKSCaptain

- type: playTimeTracker
  id: JobVKSCrewman

- type: playTimeTracker
  id: JobVKSFighterPilot

## IND

# Scav

- type: playTimeTracker
  id: JobRUScav

- type: playTimeTracker
  id: JobRUScavGuard

- type: playTimeTracker
  id: JobRUScavBoss

# Western Private Security

- type: playTimeTracker
  id: JobWPSSecurityOfficer

- type: playTimeTracker
  id: JobWPSWarden

- type: playTimeTracker
  id: JobWPSMarshal

# Civilian

- type: playTimeTracker
  id: JobCivilianUS
